### ISSUE TITLE
App not saving stock Symbol 

### ISSUE THREAD

**Issue by jamesdonnmanofaction** [shayne/stock-ticker-stream-deck-plugin#11]
When running stream deck on the latest version of OS X, the stock symbol is not saved. when configuring the button.  I have tried hitting enter, using the example symbols, but no luck.  When I leave the configuration and come back to it, the configuration is not saved and shows the the default recommendations.

**Comment by MattDierick** [comment]
Same here

MacOS 11.4
StreamDeck 5.0.0

**Comment by WBEVAN** [comment]
Same here
Mac OS 11.3.1
StreamDeck (5.0.0(14247)) 
Only occurred after upgrading to the current version of StreamDeck worked OK before and also erased prior stock symbols configured as well once upgraded. Tried the following to solve
1) removed the stock button instances
2) uninstalled
3) reinstalled

**Comment by philfreo** [comment]
Exactly the same here. Previously it was finicking but once I got it setup didn't have any issues for months until recently it lost the stock. Reinstall didn't help - can't get it to save the stock. Reinstalling didn't help. macOS 11.4

**Comment by icastillejogomez** [comment]
Same here

**Comment by simonkern** [comment]
Can confirm this on macOS 11.4

**Comment by RonaldPSA** [comment]
Same here, Stream Deck 5.0.1.14252 on Windows 10 Pro.

**Comment by b1ink0818** [comment]
Same issue here. Stream Deck 5.0.0 (14247) on macOS 10.14.6

**Comment by mattogodoy** [comment]
Same!

**Comment by mgarridobr** [comment]
Guys... it finally worked for me. The version I was installing was the 1.0.0 (Streamdeck store). it didnt work. The latest version here is 1.1.1, so I just downloaded the new one and installed it over the old. Now it works perfectly.

**Comment by mattogodoy** [comment]
Oh, it's true! Thanks a lot for letting us know :)

**Comment by b1ink0818** [comment]
Woo! 1.1.1 worked for me also, thanks for the heads up. And thank you shayne!

**Comment by philfreo** [comment]
Good find @mgarridobr 

@shayne Could you please publish the latest version to the Steamdeck store?

**Comment by shayne** [comment]
In the past they just pull it, I don't have any visibility into. I've emailed them at streamdeck.elgato@corsair.com

**Comment by tiptronic** [comment]
Hi shayne,
please prepare the plugins as mentioned here:

https://developer.elgato.com/documentation/stream-deck/sdk/exporting-your-plugin/

and send them to the mentioned email-address.

**Comment by downbytherivert** [comment]
> In the past they just pull it, I don't have any visibility into. I've emailed them at [streamdeck.elgato@corsair.com](mailto:streamdeck.elgato@corsair.com)



> Woo! 1.1.1 worked for me also, thanks for the heads up. And thank you shayne!

Superb! Thank you Shayne! Was waiting for this before I upgraded to an XL

**Comment by MattDierick** [comment]
Thanks !!!!!! It works with 1.1.1

**Comment by Monkeytactics** [comment]
Same for me, I had to replace with this Github version as described above and is working now.  Why aren't Elgato pulling this?  They're hosting an app that doesn't work.

**Comment by tiptronic** [comment]
@Monkeytactics the developers are responsible for their code they submit

**Comment by shayne** [comment]
I've reached out to Elgato to pull the latest version from releases. Should be in the main app soon.

**Comment by tiptronic** [comment]
@shayne fyi. it seems you changed the UUID of the plugin. So an update will never make it to the Stream Deck Store, because UUIDs not matching. (com.shayne.stocks -> com.exenstion.stocks). If you want an update in the Stream Deck Store (and not confuse users with changing UUIDs), you might want to change that.
