### ISSUE TITLE
Not updating

### ISSUE THREAD

**Issue by Sirwill1968** [shayne/stock-ticker-stream-deck-plugin#16]
I use it to track 1 stock.  Shows sleep blue moon.  Price is not current price.  I don' t believe it is working anymore.  Hasn't been working right for a few days.

**Comment by makeSmartio** [comment]
Same for me. Removing and re-adding the plugin fixed the issue for me.

**Comment by shayne** [comment]
Fixed in [v1.1.3](https://github.com/shayne/stock-ticker-stream-deck-plugin/releases/tag/v1.1.3)
