### ISSUE TITLE
Stock price just stopped updating

### ISSUE THREAD

**Issue by mbcooper** [shayne/stock-ticker-stream-deck-plugin#19]
Have had this working for some time.  Rebooted.  Uninstalled, re-installed.  Not working.

**Comment by unhandIedexception** [comment]
I believe the Yahoo Finance API must have changed, as the BarRaider YahooFinance stock ticker is also not working.

**Comment by shayne** [comment]
Fixed in [v1.1.3](https://github.com/shayne/stock-ticker-stream-deck-plugin/releases/tag/v1.1.3)
