### ISSUE TITLE
The plugin 'Stocks' crashed with code 0:2

### ISSUE THREAD

**Issue by mwickens** [shayne/stock-ticker-stream-deck-plugin#2]
The plug-in stopped working recently and I see these messages in the log:

```
12:00:23.8123          auto ESDCustomPlugin::StartPlugin(): Restarting plugin 'Stocks' after one minute
12:00:23.8400          void ESDCustomPluginCommunication::onMessageReceived(): Plugin 3EB6DF885D0B039847DFD730EB2DE328 is now connected
12:00:24.4620          auto ESDCustomPlugin::StartPlugin(): The plugin 'Stocks' crashed with code 0:2
12:00:24.4621          auto ESDCustomPlugin::StartPlugin(): Restarting plugin 'Stocks'
12:00:24.4706          void ESDCustomPluginCommunication::onMessageReceived(): Plugin ABE778465A35C9CA4D0E5F127CFDF301 is now connected
12:00:25.0645          auto ESDCustomPlugin::StartPlugin(): The plugin 'Stocks' crashed with code 0:2
```

Tried uninstalling, reinstalling the plug-in.

Stream Deck 4.5.1 (12246)
macOS 10.15.2 (19C57)
iMac (Retina 5K, 27-inch, 2017)

**Comment by imacnu** [comment]
Same error

**Comment by plang1997** [comment]
I was able to fix this plugin on my macbook. I have a pull request in to exension. But if you want to try it out navigate to https://github.com/plang1997/stock-ticker-stream-deck-plugin and install from the installer in the release folder. Should be able to use it on Macbook, but I didn't test it yet on windows. @randallb, @mwickens, @imacnu
