### ISSUE TITLE
Tickers not showing any prices, only default image

### ISSUE THREAD

**Issue by duffythethird** [shayne/stock-ticker-stream-deck-plugin#20]
![Capture](https://user-images.githubusercontent.com/132937370/236892598-367b4212-8d6b-4646-bfa2-c2318b10e152.PNG)

All stocks stopped working mid last week, not showing anymore prices, only the default image. I've tried swapping names/tickers, deleting entirely, putting them in new slots, uninstalling/reinstalling. Nothing appears to be working.

**Comment by zmoss** [comment]
+1, same issue for me [v1.1.3]

**Comment by duffythethird** [comment]
Looks like the Elgato Stream Deck app update that I received today fixed the issue here. Once you install the update, you'll be required to type in the Symbol again. After that it works properly.

**Comment by radzio** [comment]
@duffythethird  after streamdeck update it still does not work for me :(

**Comment by duffythethird** [comment]
bummer :/ - I did fully uninstall and then reinstall the new update. I don't know if that did anything differently, but worth trying if you haven't.

**Comment by zmoss** [comment]
I just did a full delete and reinstall version 6.2.0 (18816). Issue persists.

**Comment by hithwen** [comment]
I have the same issue, I tried updating to streamdeck 6.2.0 and unininstalling and reinstalling the plugin. The issue persists.

**Comment by jackpenny101** [comment]
+1

**Comment by mariopolo2805** [comment]
+1

**Comment by unhandIedexception** [comment]
+1

**Comment by hithwen** [comment]
Not sure if related or not, but this other ticker plugin broke too: https://github.com/Phando/Streamdeck-Stonks/issues/36

**Comment by erickzzh** [comment]
+1

**Comment by samuel-massoth** [comment]
any updates?

**Comment by mattogodoy** [comment]
@shayne Any news about this? Tickers are not working.

**Comment by shayne** [comment]
I haven't been able to repro this. So I'm using the latest version as well. Has anyone tried clearing everything out? Remove the extension and delete the old tiles and start from scratch.

**Comment by lzimmermann** [comment]
After reinstall it is still not working

**Comment by MofoMojo** [comment]
Mine has gone back to sort of working but it's not very dependable. Almost every day I have to quit Streamdeck and re-start it just to get them to work as they get "stuck" overnight and throw a caution triangle when you press them. If bar-raider is working again, I'll probably update and try it again.

**Comment by keanenwold** [comment]
> Mine has gone back to sort of working but it's not very dependable. Almost every day I have to quit Streamdeck and re-start it just to get them to work as they get "stuck" overnight and throw a caution triangle when you press them. If bar-raider is working again, I'll probably update and try it again.

Yeah, I find this issue happens when my MacBook is waking from sleep mode. Once I restart the Elgato Streamdeck software it works fine until the next 'sleep'.

**Comment by shayne** [comment]
Please download the latest release and try it with the new Finnhub API:
https://github.com/shayne/stock-ticker-stream-deck-plugin/releases/tag/v1.2.0
