### ISSUE TITLE
Stocks are not updating

### ISSUE THREAD

**Issue by justinlawrence** [shayne/stock-ticker-stream-deck-plugin#21]
Since the last update, my stocks are not updating. You'll see in the screenshot below that all the prices are the same, despite being different stocks.

<img width="288" alt="Screenshot 2023-05-17 at 09 56 04" src="https://github.com/shayne/stock-ticker-stream-deck-plugin/assets/1521183/d7f738fb-25b0-42f9-8e0a-a5b6b83a9aa0">

**Comment by lzimmermann** [comment]
For me it is the same here, is there any update for that?

**Comment by justinlawrence** [comment]
Duplicate of #25

**Comment by justinlawrence** [comment]
Duplicate of #25
