### ISSUE TITLE
Not working for a long time. 

### ISSUE THREAD

**Issue by TheSimArchitect** [shayne/stock-ticker-stream-deck-plugin#25]
Hi! I thought you were updating something to fix it, still it is not working for weeks (maybe months) here 😬

![image](https://github.com/shayne/stock-ticker-stream-deck-plugin/assets/61247454/8e14b85f-934a-4973-a0f5-1ec1f54e2fb4)

Anybody else with the same issue? It happens with or without a VPN on, so I don't believe it's a network issue.

**Comment by grizzls** [comment]
Updating to 1.1.3 worked for a while, but it's been broken again in the last few days

**Comment by phips** [comment]
Yup. Taking a look at stocks.log I see…
```
recv: {"action":"com.exension.stocks.symbol","context":"babf2db03f7b4e84033a9907194a9e67","event":"sendToPlugin","payload":{"sdpi_collection":{"checked":false,"group":false,"index":0,"key":"symbol","selection":[],"value":"SPY"}}}
API response status code non 200: 401 401 Unauthorized```

Yahoo clamping down? 🤔

**Comment by MofoMojo** [comment]
I think I replied on another thread in the last few weeks or months having similar problems but discovered it's actually working fine... however... I have to restart the Stream Deck application EVERY DAY in order to get the stocks to start working when I start work on my computer each morning.

**Comment by TheSimArchitect** [comment]
It does not work like that for me @MofoMojo

**Comment by MofoMojo** [comment]
That's a shame. For a while it was just completely broken for me... I'm having problems with all 3 of the stock related tickers myself.

**Comment by ctash-artera** [comment]
1.1.3 was working fine for me up until 2 days ago

**Comment by johannesparty** [comment]
Not working of me even; restarting app doesn't work either.

**Comment by TheSimArchitect** [comment]
> Hi! I thought you were updating something to fix it, still it is not working for weeks (maybe months) here 😬
> 
> ![image](https://user-images.githubusercontent.com/61247454/247921333-8e14b85f-934a-4973-a0f5-1ec1f54e2fb4.png)
> 
> Anybody else with the same issue? It happens with or without a VPN on, so I don't believe it's a network issue.

Same problem again. Had worked for a little while, but stopped a few weeks ago. 😬

**Comment by rubencarvalho** [comment]
Same here! Seems completely broken :(

**Comment by ardziej** [comment]
Yahoo Finance disabled API.
Based on apiURL in: https://github.com/shayne/stock-ticker-stream-deck-plugin/blob/master/pkg/api/api.go
https://query1.finance.yahoo.com/v7/finance/quote?lang=en-US&region=US&corsDomain=finance.yahoo.com&fields=symbol,marketState,regularMarketPrice,regularMarketChange,regularMarketChangePercent,preMarketPrice,preMarketChange,preMarketChangePercent,postMarketPrice,postMarketChange,postMarketChangePercent

{ finance: { result: null, error: { code: "Unauthorized", description: "Invalid Crumb. For Developers - https://bit.ly/yahoo-finance-api-feedback" } } }

We can read that the API for Yahoo Finance is disabled.
https://bit.ly/yahoo-finance-api-feedback

**Comment by TheSimArchitect** [comment]
What happens now? There's 2 plugins for stocks and they're both broken for a few months. 

Is there any free api we can use even if we have to add some sort of credential when running it?

**Comment by phips** [comment]
> I was able to use successfully the other plug-in https://github.com/BarRaider/streamdeck-stockticker

Windows only. Meh 🤷

**Comment by mgoffin** [comment]
> > I was able to use successfully the other plug-in https://github.com/BarRaider/streamdeck-stockticker
> 
> 
> 
> Windows only. Meh 🤷 

I have this installed and it only shows the bar icon when I choose either Yahoo option. Do you have to use the other service for it to work?

**Comment by whyfuture** [comment]
Awesome, thank you so much for your work. It doesn't have commodities, but it's a good step forward.
