### ISSUE TITLE
Stop working for me recently

### ISSUE THREAD

**Issue by berserksun** [shayne/stock-ticker-stream-deck-plugin#26]
Hi, 

I have been using this plugin for over last year. But it stops working recently, not sure if it's related with recent update. 

My location is in Canada.

**Comment by juleshac** [comment]
Stopped working for me too. Location uk but stocks are everywhere.

**Comment by ardziej** [comment]
Yahoo Finance disabled API.
Based on apiURL in: https://github.com/shayne/stock-ticker-stream-deck-plugin/blob/master/pkg/api/api.go
https://query1.finance.yahoo.com/v7/finance/quote?lang=en-US&region=US&corsDomain=finance.yahoo.com&fields=symbol,marketState,regularMarketPrice,regularMarketChange,regularMarketChangePercent,preMarketPrice,preMarketChange,preMarketChangePercent,postMarketPrice,postMarketChange,postMarketChangePercent

`{
finance: {
result: null,
error: {
code: "Unauthorized",
description: "Invalid Crumb. For Developers - https://bit.ly/yahoo-finance-api-feedback"
}
}
}`

We can read that the API for Yahoo Finance is disabled.
https://bit.ly/yahoo-finance-api-feedback

**Comment by whyfuture** [comment]
Indeed, needs a fix :(

**Comment by whyfuture** [comment]
@shayne maybe you could update it?

**Comment by shayne** [comment]
I'm using this daily and haven't experienced an issue. Make sure you're using the latest version from this site.

**Comment by whyfuture** [comment]
@shayne but if the Yahoo API is deprecated, how can it work? I tried 1.1.3 from the Elgato store and from Github, both don'e react to tickers or presses 

![CleanShot 2024-04-07 at 13 03 39](https://github.com/shayne/stock-ticker-stream-deck-plugin/assets/12545726/553ee787-50bc-4239-a688-5a3bff6d4c8a)

**Comment by rdohms** [comment]
Same here; it does not seem to do anything; even in the debug console, it's just not there.
I tried looking for failing requests but can't seem to find anyone.

I have removed and retried, uninstalled, and re-installed with no luck.

**Comment by whyfuture** [comment]
ironically, the store is full of awesome crypto tickers and both forex/markets stock monitors are awful and/or don't work

**Comment by whyfuture** [comment]
> <img alt="image" width="552" src="https://private-user-images.githubusercontent.com/79330/320909389-74179657-36ce-408e-8231-ed6751da3a72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxODI1OTgsIm5iZiI6MTcxMzE4MjI5OCwicGF0aCI6Ii83OTMzMC8zMjA5MDkzODktNzQxNzk2NTctMzZjZS00MDhlLTgyMzEtZWQ2NzUxZGEzYTcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDExNTgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5MzNiZTc2OTk4MWI0N2FiZmI2NDRmNTIyZDMzZWVkNTlkM2RiZjkxODZhMTVjNGJkYmE0MDA2OTBhZmZmYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3O97f0nacovDqG8PEqeDY3ELS26YEA1jAOwigJH51hM"> Meanwhile... Perhaps try clearing them out and re-adding them? I'm using the equivalent of their web APIs AFAIK and the recent updates worked around the issues with the outgoing API.

I tried, this plugin needs a rework, it doesn't work. My env isn't the problem.

**Comment by whyfuture** [comment]
> EDIT. I found the log files you write to, and in there:
> 
> > API response status code non 200: 401 401 Unauthorized

Probably people having old token have grandfathered access and new users are declined.

**Comment by shayne** [comment]
Thanks for the research. I'll look at switching providers.

**Comment by shayne** [comment]
I replaced the Yahoo Finance API with Finnhub. Please go download v1.2.0 from the releases page. I'll let Elgato know there's a new update:
https://github.com/shayne/stock-ticker-stream-deck-plugin/releases/tag/v1.2.0

**Comment by thomasriley** [comment]
Thank you @shayne very much for the update to use a different API.

1.2.0 working great for me so far.
