### ISSUE TITLE
Stocks Plugin not responsive (cannot enter symbol)

### ISSUE THREAD

**Issue by OzWanderer** [shayne/stock-ticker-stream-deck-plugin#3]
My stocks plugin does not accept any symbol. I can enter the value, but nothing happens. When I navigate away from the dialogue and come back, the symbol field is empty again. Any thoughts?

**Comment by dru5h** [comment]
I have the same issue. MBP 2019 catalina

**Comment by kaz911** [comment]
Same issue for me macOS Catalina 

It is not possible to make Stock plugin remember any symbols or even react to them.

**Comment by randallb** [comment]
I spent a bit of time looking through... not familiar enough with golang to feel productive. #2  is definitely the same as this one. I got as far as looking through the logs, the most interesting thing is in the upstream library from this one... basically `Unknown event: deviceDidConnect`. 

To look at the logs: `~/Library/Application\ Support/com.elgato.StreamDeck/Plugins/com.exension.stocks.sdPlugin/stocks.log`

and `~/Library/Logs/StreamDeck/StreamDeck0.log`

Not sure anyone else can figure it out but gl.

**Comment by plang1997** [comment]
I was able to fix this plugin on my macbook. I have a pull request in to exension. But if you want to try it out navigate to https://github.com/plang1997/stock-ticker-stream-deck-plugin and install from the installer in the release folder. Should be able to use it on Macbook, but I didn't test it yet on windows.

**Comment by kaz911** [comment]
> I was able to fix this plugin on my macbook. I have a pull request in to exension. But if you want to try it out navigate to https://github.com/plang1997/stock-ticker-stream-deck-plugin and install from the installer in the release folder. Should be able to use it on Macbook, but I didn't test it yet on windows. @randallb, @kaz911, @dru5h, @OzWanderer. @exension, @tylersmalley

thanks. On mine it works on the the first row but not on 2nd.
And if you move the field (drag it) it does not drag the Symbol with it?

but thanks for putting in the work!

**Comment by plang1997** [comment]
@kaz911, that is strange for sure, because it works fine when I do all the actions you mentioned above. Are you on a windows or mac? 15 button stream deck? My model is 20GAA9902, and I am on the very latest version of stream deck software. Are you using the version with or without the key action that launches finance.yahoo.com to the stock page?

**Comment by kaz911** [comment]
Hi,

I have tried uninstall and downloading latest ? 1.01? from your repository. No change.
MacOS latest - 15 button stream deck. Stream Desk SW 4.7 (12981) (today update) and last rev. 

I have 4 icons with stocks on top row that still shows ticks. But can't edit them. I have 2 stock icons - one on top right - and one one middle row left - which I can't edit either. 

I tried creating a new profile. I could put in one stock - after which I changed scope to the other profile - and back again - and then nothing worked again. Can't add/edit stocks on that profile. It still shows first stock (MSFT) - but can't edit that either. Clicking a stock icon on stream deck - gives yellow exclamation mark.

**Comment by kaz911** [comment]
> @kaz911, that is strange for sure, because it works fine when I do all the actions you mentioned above. Are you on a windows or mac? 15 button stream deck? My model is 20GAA9902, and I am on the very latest version of stream deck software. Are you using the version with or without the key action that launches finance.yahoo.com to the stock page?

btw - when installing the latest version the installer have no text - just first empty window with an OK button.

**Comment by kaz911** [comment]
> > @kaz911, that is strange for sure, because it works fine when I do all the actions you mentioned above. Are you on a windows or mac? 15 button stream deck? My model is 20GAA9902, and I am on the very latest version of stream deck software. Are you using the version with or without the key action that launches finance.yahoo.com to the stock page?
> 
> btw - when installing the latest version the installer have no text - just first empty window with an OK button.

hmm - that seems generic to the 4.7 release.. No text in Dialogue boxes...

**Comment by kaz911** [comment]
ok - I completely re-installed everything to latest 4.6.

It seems like if I enter a stock code that is not valid - from there on I can't add stocks or edit existing ones. I have to delete the Icon completely - and then re-add a new stock icon before I can then add any other stocks to the profile.

**Comment by kaz911** [comment]
ok - a bit more debug info.

I think one issue is - if you delete the stock icon - or move it with mouse - then it does not clear the field it came from. So if I drag from field 1 to field 3 - then behind Field 1 is still the ticker data - that now should be blank. So if that was a symbol that did not work - then that will hang all other edits to stocks. 

So missing features:
1. When drag/drop - clean departure fields for all data. Update DESTINATION data with data from Departure field (Right now it does not do that if Field had a stock symbol in it before either - then it change the stock symbol to the "hidden" symbol)

2. When deleting a Stock Icon - clean fields for all data

So as far as I can tell if you have an empty icon where there used to be a stock symbol with a wrong Symbol - it seriously impacts any other input I try to make.

**Comment by feriat** [comment]
Have same problem on Windows. Please tell if I can send some debug info

**Comment by seankda** [comment]
> I was able to fix this plugin on my macbook. I have a pull request in to exension. But if you want to try it out navigate to https://github.com/plang1997/stock-ticker-stream-deck-plugin and install from the installer in the release folder. Should be able to use it on Macbook, but I didn't test it yet on windows. @randallb, @kaz911, @dru5h, @OzWanderer. @exension, @tylersmalley

Thank you for your work! Happy to see it working again.

**Comment by MatteCrystal** [comment]
This is still broken on elgato streamdeck store. Please update it with fix.

**Comment by Tevoc** [comment]
Was there a resolution to this? I'm receiving the same error. I opened a new ticket, #5.

**Comment by Tevoc** [comment]
> Was there a resolution to this? I'm receiving the same error. I opened a new ticket, #5.

I used the above https://github.com/plang1997/stock-ticker-stream-deck-plugin and it worked! Great job!!

**Comment by Tevoc** [comment]
> > I was able to fix this plugin on my macbook. I have a pull request in to exension. But if you want to try it out navigate to https://github.com/plang1997/stock-ticker-stream-deck-plugin and install from the installer in the release folder. Should be able to use it on Macbook, but I didn't test it yet on windows. @randallb, @kaz911, @dru5h, @OzWanderer. @exension, @tylersmalley
> 
> Thank you for your work! Happy to see it working again.

@seankda Any chance you know how to make the stocks refresh on a configurable timer? I have a Crypto ticker and it refreshes...would be great if the stocks did too. :)

**Comment by shelwig** [comment]
I downloaded the plugin from the release folder of this fork and it worked great on Windows: https://github.com/plang1997/stock-ticker-stream-deck-plugin. 

Just double click the file once downloaded and it installs.

**Comment by Alchimiste-DD** [comment]
it doesn't work for me on Mac OS. It doesn't save the stock names.

**Comment by Tevoc** [comment]
> it doesn't work for me on Mac OS. It doesn't save the stock names.

Did you try this pull? https://github.com/plang1997/stock-ticker-stream-deck-plugin it worked for me.
