### ISSUE TITLE
Stock not taking Ticker Symbols

### ISSUE THREAD

**Issue by Tevoc** [shayne/stock-ticker-stream-deck-plugin#5]
Stream Deck v 4.9.2 w/ a Mac mini Catalina. 
Install of stocks without issue. Attempt to enter Ticker Symbol, but it doesn't save / stay. 
I have uninstalled and reinstalled, no love.

**Comment by Tevoc** [comment]
From Issue #3, I used this code and installed to find it worked. https://github.com/plang1997/stock-ticker-stream-deck-plugin

**Comment by jbrewlet** [comment]
Same here. On Mac 10.15.6.
